### PR TITLE
Fix wrong state when stopping playback of an AirPlay group

### PR DESCRIPTION
**Pull request by alexandreblin**
For some reason, when I stop playback to an AirPlay group containing my AirPort Express, the flags switches back to `0x4`, then again to `0x804`, even if it's not playing anything. The only differences between the two states is that the `TXT` field contains `gcgl=1`, whereas while playing, `gcgl=0`.

I'm not sure what this flag is, maybe this could break something else, I'm not sure.

### CODE REVIEW

**Comment by apexad** [comment]
Stop as in pause? or completely disconnect?
This plugin is really only 'Playing' is connected and 'Stopped' is not connected.
Please confirm.

**Comment by alexandreblin** [comment]
Yes, this happens when I completely disconnect.

When I play, I see my speakers as a group (like "Speaker 1 + Speaker 2").
When I disconnect, they split back to separate entries, then they group back together as "Speaker 1 + Speaker 2", even though I completely disconnected. This is when the flags goes back to `0x804` + `gcgl=1`

**Comment by apexad** [comment]
So, I'm willing to merge this PR, but it needs to be wrapped in a config option, maybe something like `alternateCheckDualSpeaker` as the name.  Take a look at the mDNS response in #4 for example.  The `gcgl` never changes from 0 in that example.

**Comment by JanLp** [comment]
I do not know if it is related, but I wish the "music" pause sends off status to homebridge-airport-express-playing.

**Comment by apexad** [comment]
@JanLp with the current method used by this plugin, this is not possible.

**Comment by apexad** [comment]
I've changed the method used to compare `pid` and `gid` to determine if a device is connected to the Airport Express.  This may resolve this issue since flags are no longer being used. If it does not, please adjust the PR and re-submit.

**Comment by apexad** [comment]
I actually did not mean to switch it away from flags and it caused issues.  1.4.7 reverts the change.

**Comment by apexad** [comment]
Still need to see this put into a config option before I can merge it

**Comment by apexad** [comment]
I will investigate if this change breaks other things later, but closing for now.

**Comment by apexad** [comment]
This PR can be deleted

**Pull request closed without merging**
